### ISSUE TITLE
2 - N-Gamble: notify players

### ISSUE THREAD

**Issue by shaunkatona** [decentralisedkev/SmartContractChallenges#4]
Hey Kevin,

What does this requirement mean?
`- All players should then be notified of the winner.`

You can't actively send messages/notifications to people.  Are you looking for a method that each player can call that will tell them the winner?

Thanks,
Shaun

**Comment by kevaundray** [comment]
Hi shaun,

An event will do.

**Comment by shaunkatona** [comment]
Thanks!
