### ISSUE TITLE
4 - Interest: compounding interest

### ISSUE THREAD

**Issue by shaunkatona** [decentralisedkev/SmartContractChallenges#5]
I'm still unclear on the 1% for every minute part:

`For every minute that the initial balance is in the contract, the amount increases by one percent.`

When exactly do you expect that compounding calculation to occur? The text implies every minute, but the stipulation that no 3rd party contract/timing service can be used means we must trigger this calculation manually.

Should it go in the withdraw method, compounding on the time spent between the last withdrawal? If so, before or after the transfer? If not, then in a discrete compoundInterest() method that will be called externally every minute?

Thanks,
Shaun

**Comment by kevaundray** [comment]
Yes I may have not been clear about that, it is done manually.

So when you call the contract, it will calculate the elapsed time from the last time you called the contract by using the block timestamp 'now' property. It would ideally be in every function in the contract to ensure that the correct amount is calculated each time. How you want to implement this, is up to you.

Did I explain that better?

**Comment by shaunkatona** [comment]
Yep, thanks!
