### ISSUE TITLE
2 - N-Gamble: owner participation

### ISSUE THREAD

**Issue by shaunkatona** [decentralisedkev/SmartContractChallenges#6]
Are these two requirements contradictory?
`- The owner of the contract is able to withdraw from the contract when he sees fit.`
`- Assume that the owner is not allowed to participate.`

How can the owner, who cannot participate, withdraw money (that is not theirs, no less...)?

**Comment by kevaundray** [comment]
When users participate, some amount goes to the contract itself. The owner is able to withdraw this amount. The 1%.

Sorry for the late reply, we are currently working on setting up neo smart contracts also.

Are you solely interested in ethereum smart contracts?
